name: apk

on:
  pull_request:
    branches: ["*"]
    paths:
      # Workflow file itself
      - '.github/workflows/apk.yml'
      # Rust files
      - '**.rs'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
      # database
      - "database.toml"
  push:
    branches: ["main", "develop"]
    paths:
      # Workflow file itself
      - '.github/workflows/apk.yml'
      # Rust files
      - '**.rs'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
      # database
      - "database.toml"
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}-${{github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  apk:
    runs-on: ubuntu-latest
    container:
      image: ams21/cpkg-docker:${{ matrix.version }}

    strategy:
      fail-fast: false

      matrix:
        version:
          # Alpine
          - "alpine-edge"
          - "alpine-3.20"
          - "alpine-3.19"
          - "alpine-3.18"
          - "alpine-3.17"
          - "alpine-3.16"
          - "alpine-3.15"
          - "alpine-3.14"
          - "alpine-3.13"
          - "alpine-3.12"
          - "alpine-3.11"
          - "alpine-3.10"
          - "alpine-3.9"
          # NOTE: Anything before 3.9 has too old tools and can't compile our program properly

    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@v1

      - name: Test
        run: cargo test --no-default-features --features "apk"
