name: apt

on:
  pull_request:
    branches: ["*"]
    paths:
      # Workflow file itself
      - '.github/workflows/apt.yml'
      # Rust files
      - '**.rs'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
      # database
      - "database.toml"
  push:
    branches: ["main", "develop"]
    paths:
      # Workflow file itself
      - '.github/workflows/apt.yml'
      # Rust files
      - '**.rs'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
      # database
      - "database.toml"
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}-${{github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  apt:
    runs-on: ubuntu-latest
    container:
      image: ams21/cpkg-docker:${{ matrix.version }}

    strategy:
      fail-fast: false

      matrix:
        version:
          # Debian
          - "debian-testing"
          - "debian-unstable"
          - "debian-12"
          - "debian-11"
          - "debian-10"
          - "debian-9"

          # Ubuntu
          - "ubuntu-24.04"
          - "ubuntu-23.10"
          - "ubuntu-23.04"
          - "ubuntu-22.10"
          - "ubuntu-22.04"
          - "ubuntu-21.10"
          - "ubuntu-21.04"
          - "ubuntu-20.10"
          - "ubuntu-20.04"
          - "ubuntu-19.10"
          - "ubuntu-19.04"
          - "ubuntu-18.10"
          - "ubuntu-18.04"
          - "ubuntu-17.10"
          - "ubuntu-17.04"
          - "ubuntu-16.10"
          - "ubuntu-16.04"
          - "ubuntu-15.10"
          - "ubuntu-15.04"
          - "ubuntu-14.10"
          - "ubuntu-14.04"

    steps:
      - name: Checkout
        uses: taiki-e/checkout-action@v1

      - name: Update apt
        run: apt update

      - name: Test
        run: cargo test --no-default-features --features "apt"
