name: Audit

on:
  pull_request:
    branches: ["*"]
    paths:
      # Workflow file itself
      - '.github/workflows/audit.yml'
      # Cargo files
      - '**/Cargo.lock'
      - '**/Cargo.toml'
  push:
    branches: ["main", "develop"]
    paths:
      # Workflow file itself
      - '.github/workflows/audit.yml'
      # Cargo files
      - '**/Cargo.lock'
      - '**/Cargo.toml'
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}-${{github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Audit Rust Dependencies
      uses: actions-rust-lang/audit@v1

  cargo-deny:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: EmbarkStudios/cargo-deny-action@v2
      with:
        rust-version: stable
        command: check bans licenses sources
