name: Rust

on:
  pull_request:
    branches: ["*"]
    paths:
      # Workflow file itself
      - '.github/workflows/rust.yml'
      # Rust files
      - '**.rs'
      - '**.hpp'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
  push:
    branches: ["main", "develop"]
    paths:
      # Workflow file itself
      - '.github/workflows/rust.yml'
      # Rust files
      - '**.rs'
      - '**.hpp'
      # Cargo files
      - 'Cargo.lock'
      - 'Cargo.toml'
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}-${{github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: clippy

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5

    - name: Clippy
      run: cargo hack clippy --feature-powerset --verbose -- -D warnings

  audit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5

    - name: Audit Rust Dependencies
      uses: actions-rust-lang/audit@v1

  formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        components: rustfmt

    - name: Rustfmt Check
      uses: actions-rust-lang/rustfmt@v1

  build:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

      matrix:
        toolchain:
          - "nightly"
          - "beta"
          - "stable"
          - "1.79.0"
          - "1.78.0"
          - "1.77.2"
          - "1.77.1"
          - "1.77.0"
          - "1.76.0"
          - "1.75.0"
          - "1.74.1"
          - "1.74.0"

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1
      with:
        toolchain: ${{ matrix.toolchain }}

    - uses: taiki-e/install-action@v2
      with:
        tool: cargo-hack

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5

    - name: Run tests
      run: cargo hack test --feature-powerset --verbose
