name: StyleCheck

on:
  pull_request:
    branches: ["*"]
  push:
    branches: ["main", "develop"]
  workflow_dispatch:

concurrency:
  # Documentation suggests ${{ github.head_ref }}, but that's only available on pull_request/pull_request_target triggers, so using ${{ github.ref }}.
  # On main, we want all builds to complete even if merging happens faster to make it easier to discover at which point something broke.
  group: ${{ github.ref == 'refs/heads/main' && format('ci-main-{0}', github.sha) || format('ci-{0}', github.ref) }}-${{github.workflow }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: "true"
  RUSTC_WRAPPER: "sccache"

jobs:
  toml-formatting:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install rust toolchain
      uses: actions-rust-lang/setup-rust-toolchain@v1

    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.5

    - name: Install taplo
      run: cargo install taplo-cli --locked

    - name: Run Taplo
      id: taplo
      run: taplo fmt --check --diff

    - name: Taplo info
      if: failure()
      run: |
          echo 'To fix toml fmt, please run `taplo fmt`'
          echo 'To check for a diff, run `taplo fmt --check --diff'
          echo 'You can find taplo here: https://taplo.tamasfe.dev/'
          echo 'Or if you use VSCode, use the `Even Better Toml` extension with 2 spaces'
          echo 'You can find the extension here: https://marketplace.visualstudio.com/items?itemName=tamasfe.even-better-toml'

  typos:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@v1.24.1

      - name: Typos info
        if: failure()
        run: |
          echo 'To fix typos, please run `typos -w`'
          echo 'To check for a diff, run `typos`'
          echo 'You can find typos here: https://crates.io/crates/typos'
          echo 'if you use VSCode, you can also install `Typos Spell Checker'
          echo 'You can find the extension here: https://marketplace.visualstudio.com/items?itemName=tekumara.typos-vscode'
